/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'businessType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const InquiryId = IDL.Nat;

export const idlService = IDL.Service({
  'getAllContacts' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], []),
  'getInquiryById' : IDL.Func([IDL.Text, InquiryId], [Inquiry], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [InquiryId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'businessType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const InquiryId = IDL.Nat;
  
  return IDL.Service({
    'getAllContacts' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], []),
    'getInquiryById' : IDL.Func([IDL.Text, InquiryId], [Inquiry], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [InquiryId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };